eCare2/eCare/src/main/java/ru/tsystems/ecare/dto/ContractDTO.java
package ru.tsystems.ecare.dto;

import ru.tsystems.ecare.entities.Contract;

import javax.validation.constraints.Size;
import java.util.List;

/**
 * DTO for contracts
 */
public class ContractDTO {

    public ContractDTO() {};

    public ContractDTO(Contract contract) {
        id = contract.getId();
        phoneNumber = contract.getPhoneNumber();
        isActive = contract.isActive();
        whoBlocked = contract.isWhoBlocked();
    }

    private Long id;

    @Size(min = 1)
    private String phoneNumber;

    private boolean isActive;

    private boolean whoBlocked;

    private TariffDTO tariff;

    private List<OptionDTO> selectedOptions;

    public Long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public boolean isActive() {
        return isActive;
    }

    public void setActive(boolean isActive) {
        this.isActive = isActive;
    }

    public boolean isWhoBlocked() {
        return whoBlocked;
    }

    public void setWhoBlocked(boolean whoBlocked) {
        this.whoBlocked = whoBlocked;
    }

    public List<OptionDTO> getSelectedOptions() {
        return selectedOptions;
    }

    public void setSelectedOptions(List<OptionDTO> selectedOptions) {
        this.selectedOptions = selectedOptions;
    }

    public TariffDTO getTariff() {
        return tariff;
    }

    public void setTariff(TariffDTO tariff) {
        this.tariff = tariff;
    }
}

eCare2/eCare/src/main/java/ru/tsystems/ecare/controllers/ManagerController.java
package ru.tsystems.ecare.controllers;

import com.google.gson.Gson;
import com.google.gson.JsonObject;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.*;
import ru.tsystems.ecare.dto.ContractDTO;
import ru.tsystems.ecare.dto.OptionDTO;
import ru.tsystems.ecare.dto.TariffDTO;
import ru.tsystems.ecare.dto.UserDTO;
import ru.tsystems.ecare.dto.request.*;
import ru.tsystems.ecare.entities.Contract;
import ru.tsystems.ecare.entities.Option;
import ru.tsystems.ecare.entities.Tariff;
import ru.tsystems.ecare.entities.User;
import ru.tsystems.ecare.services.ContractService;
import ru.tsystems.ecare.services.OptionService;
import ru.tsystems.ecare.services.TariffService;
import ru.tsystems.ecare.services.UserService;

import javax.validation.Valid;
import java.util.ArrayList;
import java.util.List;

/**
 * Class for processing manager's responses
 */
@Controller
@RequestMapping("/manager")
public class ManagerController {

    @Autowired
    private UserService userService;

    @Autowired
    private TariffService tariffService;

    @Autowired
    private ContractService contractService;

    @Autowired
    private OptionService optionService;

    /**
     * return private information for manager
     * @param map
     * @return path to view
     */
    @RequestMapping({"","/index"})
    public String index(ModelMap map) {
        User user = userService.getUserByLogin(getUserName());
        map.put("user", user);
        return "manager/index";
    }

    /**
     * return information about tariffs and options  for manager
     * @param map
     * @return path to view
     */
    @RequestMapping("/tariffsAndOptions")
    public String tariffsAndOptions(ModelMap map) {
        map.put("allTariffs",getAllTariffsDTO(tariffService.getAllTariff(),true));
        return "manager/tariffsAndOptions";
    }

    /**
     * return view with all users
     * @param map
     * @return path to view
     */
    @RequestMapping("/allContracts")
    public String allContracts(ModelMap map) {
        List<User> users = userService.getAllClients();
        List<UserDTO> usersDTOList = new ArrayList<>();
        for(User user : users)
            usersDTOList.add(new UserDTO(user));
        map.put("users",usersDTOList);
        return "manager/allContracts";
    }

    /**
     * Return users having contacts with number
     * @param map
     * @param number of contract, which we want find
     * @return path to view
     */
    @RequestMapping(value = "/allContracts/search",method = RequestMethod.GET)
    public String allContractsByPhone(ModelMap map,@RequestParam("number") String number) {
        List<User> users = userService.getUserByPhone(number);
        List<UserDTO> usersDTOList = new ArrayList<>();
        for(User user : users)
            usersDTOList.add(new UserDTO(user));
        map.put("users",usersDTOList);
        return "manager/allContracts";
    }

    /**
     *
     * @param map
     * @param userId unique user's number for getting contracts
     * @return path to view, where we can see user`s contracts
     */
    @RequestMapping("/allContracts/user/{id}")
    public String userContract(ModelMap map,@PathVariable("id") Long userId) {
        User user = userService.getUserById(userId);
        map.put("userId",user.getId());
        map.put("userContracts",getContractDTOList(user.getContracts()));
        map.put("allTariffs",getAllTariffsDTO(tariffService.getAllTariff(),false));
        return "manager/userContracts";
    }

    /**
     * Method for saving user's contract
     * @param request Object, with nessesary data
     * @return message of operation
     */
    @RequestMapping(value = "allContracts/user/contracts/save", method = RequestMethod.POST,
            consumes="application/json")
    public @ResponseBody
    String saveContract(@RequestBody SaveContractRequestDTO request) {
        contractService.saveContract(request.getIdContract(),request.getIdTariff(),
                request.getOptions(),request.isActive(),true);
        return "success";
    }

    /**
     * Method for creating new tariff
     * @param tariffDTO DTO for entity Tariff
     * @return message of operation
     */
    @RequestMapping(value = "allContracts/tariffs/create", method = RequestMethod.POST,
            consumes="application/json")
    public @ResponseBody
    String createTariff(@RequestBody @Valid TariffDTO tariffDTO) {
        Tariff tariff = new Tariff();
        tariff.setName(tariffDTO.getName());
        tariff.setPrice(tariffDTO.getPrice());
        tariffService.createTariff(tariff);
        return "success";
    }

    @RequestMapping(value = "/allContracts/user/{id}/contracts/create", method = RequestMethod.POST,
            consumes="application/json")
    public @ResponseBody
    String createContract(@RequestBody @Valid ContractDTO requestDTO,@PathVariable("id") long userId) {
        Contract contract =new Contract();
        contract.setPhoneNumber(requestDTO.getPhoneNumber());
        contract.setActive(requestDTO.isActive());
        contract.setWhoBlocked(requestDTO.isWhoBlocked());
        contractService.createContract(contract, userId);
        return "success";
    }

    /**
     * CMethod for creating user
     * @param user DTO for entity user
     * @return message of operation
     */
    @RequestMapping(value = "allContracts/users/create", method = RequestMethod.POST,
            consumes="application/json")
    public @ResponseBody
    String createUser(@RequestBody @Valid SaveUserRequestDTO user) {
        User newUser = new User();
        newUser.setName(user.getUser().getName()); newUser.setAddress(user.getUser().getAddress());
        newUser.setBirthdayDate(user.getUser().getBirthdayDate()); newUser.setEmail(user.getUser().getEmail());
        newUser.setSurname(user.getUser().getSurname());newUser.setPassport(user.getUser().getPassport());
        newUser.setRole(user.isRole()); newUser.setRole(user.isRole());newUser.setPassword(user.getPassword());
        userService.createUser(newUser);
        return "success";
    }

    /**
     * MEthod for creating option
     * @param optionRequestDTO DTO contains data for create option
     * @return id created option
     */
    @RequestMapping(value = "allContracts/options/create", method = RequestMethod.POST,
            consumes="application/json")
    public @ResponseBody
    String createOption(@RequestBody @Valid CreateOptionRequestDTO optionRequestDTO) {
        Option option = new Option();
        option.setName(optionRequestDTO.getName());
        option.setPrice(optionRequestDTO.getPrice());
        option.setCost(optionRequestDTO.getCost());
        optionService.createOption(option,optionRequestDTO.getIdTariff());
        JsonObject jsonElement = new JsonObject();
        jsonElement.addProperty("status","success");
        jsonElement.addProperty("idOption",option.getId());
        Gson gson = new Gson();
        return gson.toJson(jsonElement);
    }

    /**
     * Method for creating user
     * @param request DTO with data for create rule
     * @return message of operation
     */
    @RequestMapping(value = "tariffsAndOptions/rule/create", method = RequestMethod.POST,
            consumes="application/json")
    public @ResponseBody
    String createRule(@RequestBody RuleRequestDTO request) {
        optionService.createRule(request.getIdOption1(),request.getIdOption2(),request.isCompatible());
        return "success";
    }

    /**
     * Method for remove option's rule
     * @param request
     * @return
     */
    @RequestMapping(value = "tariffsAndOptions/rule/remove", method = RequestMethod.POST,
            consumes="application/json")
    public @ResponseBody
    String removeRule(@RequestBody RuleRequestDTO request) {
        optionService.removeRule(request.getIdOption1(),request.getIdOption2(),request.isCompatible());
        return "success";
    }

    /**
     * Remove option
     * @param id unique number by option, by which will be remove
     * @return message operation
     */
    @RequestMapping(value = "tariffsAndOptions/option/remove/{id}")
    public @ResponseBody
    String removeOption(@PathVariable("id") long id) {
        optionService.removeOption(id);
        return "success";
    }

    /**
     * Remove tariff
     * @param id  unique tariff`s name
     * @return message of operation
     */
    @RequestMapping(value = "tariffsAndOptions/tariff/remove/{id}")
    public @ResponseBody
    String removeTariff(@PathVariable("id") long id) {
        tariffService.removeTariff(id);
        return "success";
    }

    /**
     * Remove user
     * @param id unique user`s number
     * @return message of operation
     */
    @RequestMapping(value = "allContracts/user/remove/{id}")
    public @ResponseBody
    String removeUser(@PathVariable("id") long id) {
        userService.removeUser(id);
        return "success";
    }

    /**
     * Removing contract
     * @param id
     * @return
     */
    @RequestMapping(value = "allContracts/user/contracts/remove/{id}",method = RequestMethod.POST)
    public @ResponseBody
    String removeContract(@PathVariable("id") long id) {
        contractService.removeContract(id);
        return "success";
    }


    private List<TariffDTO> getAllTariffsDTO(List<Tariff> allTariffs, boolean init) {
        List<TariffDTO> tariffDTOList = new ArrayList<>();
        for(Tariff tariff : allTariffs) {
            TariffDTO tariffDTO = new TariffDTO(tariff);

eCare2/eCare/src/main/webapp/WEB-INF/views/manager/addDeleteContracts.jsp
<button id = "addContract" type="button" class="btn btn-success dropdown-toggle">Add</button>
<button type="button" class="btn btn-danger dropdown-toggle universalButton" id="deleteContract">
    Delete
</button>
<div class="modal fade" id="addContractsModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span
                        class="sr-only">Close</span></button>
                <h4 class="modal-title">Add Contract</h4>
            </div>
            <div class="modal-body">
                <div>
                    <label class="contract-label">
                        Phone Number:
                    </label>
                    <input type="text" class="contract-field" id = "new_contract_number">
                </div>
            </div>
            <div class="modal-footer">
                <button id="add_new_contract" type="button" class="btn btn-success dropdown-toggle contract-button">
                    Add
                </button>
            </div>
        </div>
    </div>
</div>

eCare2/eCare/src/main/webapp/WEB-INF/views/manager/allContracts.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@taglib uri="http://www.springframework.org/tags" prefix="spring" %>
<%@taglib uri="http://www.springframework.org/tags/form" prefix="form" %>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <%@ include file="/WEB-INF/views/layouts/_manager_head.jsp" %>
    <link rel="stylesheet" type="text/css"
          href="${pageContext.request.contextPath}/css/bootstrap/jquery.dataTables.css"/>
    <link rel="stylesheet" type="text/css"
          href="${pageContext.request.contextPath}/css/bootstrap/datepicker.css"/>
    <link rel="stylesheet" type="text/css" href="${pageContext.request.contextPath}/css/allContracts.css"/>

    <script type="text/javascript" language="javascript"
            src="${pageContext.request.contextPath}/js/libs/jquery.dataTables.js"></script>
    <script type="text/javascript" language="javascript"
            src="${pageContext.request.contextPath}/js/allContracts.js"></script>
    <script type="text/javascript" language="javascript"
            src="${pageContext.request.contextPath}/js/objects.js"></script>
    <script type="text/javascript" language="javascript"
            src="${pageContext.request.contextPath}/js/libs/bootstrap/dataTables.bootstrap.js"></script>
    <script type="text/javascript" language="javascript"
            src="${pageContext.request.contextPath}/js/libs/bootstrap/bootstrap-datepicker.js"></script>
    <script type="text/javascript" language="javascript">
        <c:forEach items="${users}" var="user">
            users["${user.id}"] = new UserECare("${user.id}","${user.name}","${user.surname}",
                    new Date("${user.birthdayDate}"),"${user.passport}","${user.address}","${user.email}",[],false);
        </c:forEach>
    </script>
</head>
<body>
<div id="error_block">
    <div id="error_message" class="alert alert-danger alert-dismissible" role="alert">
        <button id="close_message" type="button" class="close"><span aria-hidden="true">&times;</span><span
                class="sr-only">Close</span></button>
        <strong>Error!</strong> <span id="error_message_text"></span>
    </div>
</div>
<div class="main_block">
    <c:set var="activeMenu" value="contracts" />
    <%@ include file="/WEB-INF/views/layouts/_manager_body.jsp" %>
    <div id="title_user">Users</div>
    <div class="container">
        <div id="search_block">
            <label for="searchField" id="searchLabel">Search (phone)</label>
            <input class="characteristic_field" type="text" id="searchField">
            <button type="button" class="btn btn-info" id="search_button">Search</button>
        </div>
        <table class="table" id="userTable">
            <thead>
            <tr>
                <th>Name</th>
                <th>Surname</th>
                <th>Email</th>
                <th>Birthday</th>
                <th>Passport</th>
            </tr>
            </thead>
            <tbody id="users">
            </tbody>
        </table>
        <button id = "add_new_user_button" type="button" class="btn btn-success dropdown-toggle">Add user</button>
        <button type="button" class="btn btn-danger dropdown-toggle universalButton" id="deleteUserButton">
            Delete
        </button>
        <button type="button" class="btn btn-info dropdown-toggle universalButton" id="showContracts">
            Show/Change contracts
        </button>
    </div>
    <%@ include file="/WEB-INF/views/layouts/_footer.jsp" %>
</div>
<div class="modal fade" id="addNewUserModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span
                        class="sr-only">Close</span></button>
                <h4 class="modal-title">Add new user</h4>
            </div>
            <div class="modal-body">
                <div id="profile">
                    <label class="profile_label">Name:</label>
                    <input type="text" class="user_field" id="new_user_name">
                    <br>
                    <label class="profile_label">Surname:</label>
                    <input type="text" class="user_field" id="new_user_surname">
                    <br>
                    <label class="profile_label">Birthday:</label>
                    <input type="text" class="user_field" id="new_user_birthday">
                    <br>
                    <label class="profile_label">Passport:</label>
                    <input type="text" class="user_field" id="new_user_passport">
                    <br>
                    <label class="profile_label">Address:</label>
                    <input type="text" class="user_field" id="new_user_address">
                    <br>
                    <label class="profile_label">Email:</label>
                    <input type="email" class="user_field" id="new_user_email">
                    <br>
                    <label class="profile_label">Password:</label>
                    <input type="text" class="user_field" id="new_user_password">
                    <br>
                    <label class="profile_label">Manager</label>
                    <input type="checkbox" class="user_field" id="new_user_role">
                </div>
            </div>
            <div class="modal-footer">
                <button id="addUserButton" type="button" class="btn btn-success dropdown-toggle">Add</button>
            </div>
        </div>
    </div>
</div>
</body>
</html>

eCare2/eCare/src/main/webapp/WEB-INF/views/manager/index.jsp

<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@taglib uri="http://www.springframework.org/tags" prefix="spring"%>
<%@taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <%@ include file="/WEB-INF/views/layouts/_manager_head.jsp" %>
    <link rel="stylesheet" type="text/css" href="${pageContext.request.contextPath}/css/personal_cabinet.css" />
</head>
<body>
<div class = "main_block">
    <c:set var="activeMenu" value="index" />
    <%@ include file="/WEB-INF/views/layouts/_manager_body.jsp" %>
    <div class = "data clearfix">
        <div id ="personal_data">
            <h2>Your personal data:</h2>
            <p><img src="${pageContext.request.contextPath}/img/manager.png" width ="150px" height = "180px" id = "user_image"></p>
            <div id = "profile">
                <label class = "profile_label">Name:</label>
                <input type="text" class="user_field" id = "user_name" value = "${user.getName()}" disabled="disabled">
                <br>
                <label class = "profile_label">Surname:</label>
                <input type="text" class="user_field" id = "user_surname" value = "${user.getSurname()}" disabled="disabled">
                <br>
                <label class = "profile_label">Birthday:</label>
                <input type="text" class="user_field" id = "birthday" value = "${user.getBirthdayDate()}" disabled="disabled">
                <br>
                <label class = "profile_label">Passport:</label>
                <input type="text" class="user_field" id = "passport" value = "${user.getPassport()}" disabled="disabled">
                <br>
                <label class = "profile_label">Address:</label>
                <input type="text" class="user_field" id = "address" value = "${user.getAddress()}" disabled="disabled">
                <br>
                <label class = "profile_label">Email:</label>
                <input type="text" class="user_field" id = "email" value = "${user.getEmail()}" disabled="disabled">
            </div>
        </div>
    </div>
    <%@ include file="/WEB-INF/views/layouts/_footer.jsp" %>
</div>
</body>
</html>

eCare2/eCare/src/main/webapp/WEB-INF/views/manager/userContracts.jsp
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <%@ include file="/WEB-INF/views/layouts/_manager_head.jsp" %>
    <link rel="stylesheet" type="text/css" href="${pageContext.request.contextPath}/css/bootstrap/bootstrap-select.css">
    <link rel="stylesheet" type="text/css" href="${pageContext.request.contextPath}/css/user-contracts.css"/>
    <script type="text/javascript"
            src="${pageContext.request.contextPath}/js/libs/bootstrap/bootstrap-select.js"></script>
    <script type="text/javascript" src="${pageContext.request.contextPath}/js/objects.js"></script>
    <script type="text/javascript" src="${pageContext.request.contextPath}/js/libs/jquery.session.js"></script>
    <script type="text/javascript" src="${pageContext.request.contextPath}/js/add_contracts.js"></script>
    <script type="text/javascript" src="${pageContext.request.contextPath}/js/addDeleteContracts.js"></script>
    <script id="forRemove" type="text/javascript">
        USER_ID = ${userId};
        <c:forEach items="${userContracts}" var="contract">
            var tariffOptions = [];
            var cOptions = [];
            var iOptions = [];
            <c:forEach items="${contract.tariff.options}" var="option">
            cOptions = [];
            iOptions = [];
            <c:forEach items="${option.incompatibleOptions}" var="iOption">
            iOptions["${iOption.id}"]=new OptionECare("${iOption.id}","${iOption.name}",
                    ${iOption.cost},${iOption.price},[],[]);
            </c:forEach>
            <c:forEach items="${option.compatibleOptions}" var="cOption">
            cOptions["${cOption.id}"]=new OptionECare("${cOption.id}","${cOption.name}",
                    ${cOption.cost},${cOption.price},[],[]);
            </c:forEach>
            tariffOptions["${option.id}"]=new OptionECare("${option.id}","${option.name}",
                    ${option.cost},${option.price},cOptions,iOptions);

            </c:forEach>
            var tariff = new TariffECare(${contract.tariff.id},"${contract.tariff.name}",${contract.tariff.price},tariffOptions);
            var contractOptions = [];
            <c:forEach items="${contract.selectedOptions}" var="option">
            cOptions = [];
            iOptions = [];
            <c:forEach items="${option.incompatibleOptions}" var="iOption">
            iOptions["${iOption.id}"]=new OptionECare("${iOption.id}","${iOption.name}",
                    ${iOption.cost},${iOption.price},[],[]);
            </c:forEach>
            <c:forEach items="${option.compatibleOptions}" var="cOption">
            cOptions["${cOption.id}"]=new OptionECare("${cOption.id}","${cOption.name}",
                    ${cOption.cost},${cOption.price},[],[]);
            </c:forEach>
            contractOptions.push(new OptionECare("${option.id}","${option.name}",
                    ${option.cost},${option.price},cOptions,iOptions));
            </c:forEach>
            var contract = new ContractECare(${contract.id},"${contract.phoneNumber}",${contract.active},
                    ${contract.whoBlocked},tariff,contractOptions);
            contracts[contract.phoneNumber]=contract;
        </c:forEach>

        <c:forEach items="${allTariffs}" var="tariff">
            tariffOptions = [];
            <c:forEach items="${tariff.options}" var="option">
            cOptions = [];
            iOptions = [];
            <c:forEach items="${option.incompatibleOptions}" var="iOption">
            iOptions["${iOption.id}"]=new OptionECare("${iOption.id}","${iOption.name}",
                    ${iOption.cost},${iOption.price},[],[]);
            </c:forEach>
            <c:forEach items="${option.compatibleOptions}" var="cOption">
            cOptions["${cOption.id}"]=new OptionECare("${cOption.id}","${cOption.name}",
                    ${cOption.cost},${cOption.price},[],[]);
            </c:forEach>
            tariffOptions["${option.id}"]=new OptionECare("${option.id}","${option.name}",
                    ${option.cost},${option.price},cOptions,iOptions);

            </c:forEach>
            tariff = new TariffECare(${tariff.id},"${tariff.name}",${tariff.price},tariffOptions);
            allTariffs[tariff.name]=tariff;
        </c:forEach>
    </script>
</head>
<body>
<c:set var="activeMenu" value="contracts"/>
<div id="error_block">
    <div id="error_message" class="alert alert-danger alert-dismissible" role="alert">
        <button id="close_message" type="button" class="close"><span
                aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <strong>Error!</strong> <span id="error_message_text"></span>
    </div>
</div>
<div id="info_block">
    <div id = "info_message" class="alert alert-success alert-dismissible" role="alert">
        <button id="close_info_message" type="button" class="close"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <span id="info_message_text"></span>
    </div>
</div>
<div class="main_block">
    <%@ include file="/WEB-INF/views/layouts/_manager_body.jsp" %>
    <div id="contracts_selection">
        <div id=switch_block class="onoffswitch">
            <input id="block_check" type="checkbox" name="onoffswitch" class="onoffswitch-checkbox" id="myonoffswitch"
                   checked>
            <label class="onoffswitch-label" for="myonoffswitch">
                <span class="onoffswitch-inner"></span>
                <span class="onoffswitch-switch"></span>
            </label>
        </div>
        <span id="is_blocked">Blocked</span>

        <div id="contracts_label">
            <label>Contracts</label>
            <select class="selectpicker show-tick" id="contracts">
            </select>
        </div>
        <button type="button" class="btn btn-success dropdown-toggle contract-button clearfix" id="saveButton">Save
        </button>
    </div>
    <c:if test="${!empty userContracts}">
        <div id="contract_info_block">
            <div id="tariff_block">
                <label class="tariff_label">Tariff</label>
                <br>
                <label class="characteristic_label">
                    Name:
                </label>
                <select disabled class="characteristic_field" id="tariff_name">
                </select>
                <button type="button" class="btn btn-success dropdown-toggle" id="change_tariff_button">Ok</button>
                <br>
                <label class="characteristic_label">
                    Price:
                </label>
                <input type="text" class="characteristic_field" id="price" value="5555" disabled="disabled">
                <br>
                <button type="button" class="btn btn-success dropdown-toggle contract-button" id="change_button">
                    Change
                </button>
                <button type="button" class="btn btn-danger contract-button" id="cancel_change_tariff_button">Cancel
                </button>
            </div>
            <div id="options_block">
                <label class="tariff_label">
                    Options:
                </label>
                <br>
                <table class="table table-bordered" id="options_table">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Cost</th>
                        <th>Price</th>
                    </tr>
                    </thead>
                    <tbody id="selected_options">
                    </tbody>
                </table>
                <button type="button" class="btn btn-success dropdown-toggle contract-button" id="add_button">Add
                </button>
                <button type="button" class="btn btn-danger dropdown-toggle contract-button" id="delete_button">Delete
                </button>
            </div>

        </div>

        <%@ include file="/WEB-INF/views/manager/addDeleteContracts.jsp" %>

        <div class="modal fade" id="addOptionsModal">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span
                                class="sr-only">Close</span></button>
                        <h4 class="modal-title">Add options</h4>
                    </div>
                    <div class="modal-body">
                        <div>
                            <label class="characteristic_label" id="modal_characteristic_label">
                                Tariff:
                            </label>
                            <input type="text" class="characteristic_field" value="tariff_0" disabled="disabled"
                                   id="modal_characteristic_field">
                        </div>
                        <div>
                            <ul class="list-group">
                                <li class="list-group-item disabled">Options</li>
                                <div id="options_list">
                                </div>
                            </ul>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button id="add_option" type="button" class="btn btn-success dropdown-toggle contract-button">
                            Add
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </c:if>

    <%@ include file="/WEB-INF/views/layouts/_footer.jsp" %>
</div>
</body>
</html>